# Generated by Django 4.0 on 2022-05-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('func_name', models.CharField(max_length=255)),
                ('lineno', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='SaveSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_location_code', models.CharField(max_length=64, verbose_name='originLocationCode')),
                ('destination_location_code', models.CharField(max_length=64, verbose_name='destinationLocationCode')),
                ('departureDate', models.DateField(verbose_name='departureDate')),
                ('returnDate', models.DateField(blank=True, null=True, verbose_name='returnDate')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='adults')),
                ('children', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='children')),
                ('infants', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='infants')),
                ('travelClass', models.CharField(max_length=255, verbose_name='travelClass')),
                ('currency_code', models.CharField(default='RUB', max_length=64, verbose_name='currencyCode')),
                ('validatingAirlineCodes', models.CharField(max_length=64, verbose_name='validatingAirlineCodes')),
                ('nonStop', models.CharField(default=False, max_length=64, verbose_name='nonStop')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='total')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='add_time')),
                ('route', models.JSONField(verbose_name='route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'Истории поиска',
                'ordering': ['-add_time'],
            },
        ),
    ]
