# Generated by Django 4.0 on 2022-03-30 16:57

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнёрский маркер')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хост')),
                ('user_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP пользователя')),
                ('locale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локализация')),
                ('trip_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Класс перелета')),
                ('adults', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Количество взрослых')),
                ('children', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Количество детей')),
                ('infants', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Количество младенцев')),
                ('know_english', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Знание английского языка')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стоимость')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'Истории поиска',
                'ordering': ['-add_time'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Дата отправления')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='IATA-код пункта отправления')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='IATA-пункта назначения')),
                ('user_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.userrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Сегмент',
                'verbose_name_plural': 'Сегменты',
                'ordering': ['-travel_date'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
