# Generated by Django 4.0 on 2022-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Данный адресс уже используется.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
